services:
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 20d & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/dist:/dist
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always

  certbot:
    build: 
      context: ./certbot
      dockerfile: Dockerfile
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 10d & wait $${!}; done;'"
    volumes:
      - ./nginx/dist:/dist
      - /etc/letsencrypt:/etc/letsencrypt
    command: ["--version"]
    restart: always
